name: Test Python Code
on: [push]
jobs:
  Test-Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: cd Software/OnlineLearning/ && uv sync
      - run: cd Software/OnlineLearning/ && puv run ytest

  Type-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: cd Software/OnlineLearning/ && uv sync
      - run: cd Software/OnlineLearning/ && uv run pyright

  Lint-And-Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: cd Software/OnlineLearning/ && uv sync
      - run: cd Software/OnlineLearning/ && uv run ruff --check
